# Generated by Django 3.0.8 on 2020-07-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_suggestion', '0002_auto_20200721_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdb_id',
            field=models.CharField(default='', max_length=20),
        ),
    ]
